# Generated by Django 2.2 on 2020-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200720_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
